#!/bin/bash
#
#PBS -N meshes_20190809_pre1_d18_intAdj_rep1ds1gd_rf
#PBS -A UQ-IMB
#PBS -l select=1:ncpus=2:mpiprocs=2:mem=10GB,walltime=5:00:00
#

# DESCRIPTION
#  PBS array job calling the groovy script get_meshes.groovy
#  

(sleep $(( ($PBS_ARRAY_INDEX % 10) * 15 )))

numberStacksPerJob=10
lastStack=$(( ($numberStacksPerJob)*($PBS_ARRAY_INDEX) ))
firstStack=$(( ($lastStack)-($numberStacksPerJob)+1 ))

echo "job "$PBS_ARRAY_INDEX" stacks "$firstStack" - "$lastStack

~/Fiji.app/ImageJ-linux64 --ij2 --headless --allow-multiple --run ~/code/get_meshes.groovy \
"imageStackLocation='/30days/uqjlefev/20190809/Pre1/segmentation/d18_intAdj_rep1ds1gd_rf/objectAnalysis/',"\
"savePath='/30days/uqjlefev/20190809/Pre1/segmentation/d18_intAdj_rep1ds1gd_rf/objectAnalysis/',"\
"firstStackNumber='$firstStack',"\
"lastStackNumber='$lastStack',"\
"stackNumberPrefix='-t',"\
"stackNumberSuffix='-e',"\
"numberThreadsToUse='2',"\
"fileNamePrefix='c1-',"\
"overwriteExisting='false',"\
"targetMeshVertexReduction='[0.96,0.0,0.8,0.8]',"\
"meshSmoothingIterations='[0,0,0,0]'"

exit 0
