#!/bin/bash
#
#PBS -N sync_seg_to_scratch_20190809_post1
#PBS -A UQ-IMB
#PBS -l select=1:ncpus=1:mpiprocs=1:mem=2GB,walltime=2:00:00

dataset="20190809/Post1"
mkdir -p "/30days/uqjlefev/"$dataset"/segmentation/d18_intAdj_rep1ds1gd_rf/segmented/"
rsync -rv --include="*/" --include="*.tif" --include="*.tiff" --exclude="*" "/RDS/Q0930/MachineLearning_ARC_Grant_work/"$dataset"/segmentation/d18_intAdj_rep1ds1gd_rf/segmented/" "/30days/uqjlefev/"$dataset"/segmentation/d18_intAdj_rep1ds1gd_rf/segmented/"

exit 0
