#!/bin/bash
#
#PBS -N sync_decon_to_scratch_20190809_post2
#PBS -A UQ-IMB
#PBS -l select=1:ncpus=1:mpiprocs=1:mem=2GB,walltime=2:00:00

dataset="20190809/Post2"
mkdir -p "/30days/uqjlefev/"$dataset"/Decon_output/"
rsync -rv --include="*/" --include="*.tif" --include="*.tiff" --exclude="*" "/RDS/Q0930/MachineLearning_ARC_Grant_work/"$dataset"/Decon_output/" "/30days/uqjlefev/"$dataset"/Decon_output/"

exit 0
