#!/bin/bash
#
#PBS -N object_detection
#PBS -A Your_Account_String
#PBS -l select=1:ncpus=6:mpiprocs=6:mem=120GB,walltime=3:00:00

(sleep $(( ($PBS_ARRAY_INDEX % 10) * 15 )))

numberStacksPerJob=1
lastStack=$(( ($numberStacksPerJob)*($PBS_ARRAY_INDEX) ))
firstStack=$(( ($lastStack)-($numberStacksPerJob)+1 ))

echo "job "$PBS_ARRAY_INDEX" stacks "$firstStack" - "$lastStack

~/Fiji.app/ImageJ-linux64 --ij2 --headless --allow-multiple --run ~/code/split_object_analysis.groovy \
"imageStackLocation='/outputs/segmented/',"\
"originalStackLocation='/images/',"\
"probStackLocation='/outputs/probability_maps/',"\
"savePath='/outputs/objects/',"\
"firstStackNumber='$firstStack',"\
"lastStackNumber='$lastStack',"\
"numberThreadsToUse='6',"\
"stackNumberPrefix='e',"\
"stackNumberSuffix='_c',"\
"overwriteExisting='false',"\
"classNumsToFill=[2,3],"\
"classesToAnalyse=[1,2,3],"\
"classLayers=[1,2,2],"\
"incorporatedChannels=[[1],[2],[3]],"\
"dynamic=[200,10,10],"\
"minVoxExtraObjects=75,"\
"channelsForDistanceMap=[2,3],"\
"smoothingErosionForDistanceMap=[20,20],"\
"intensityScalingFactor=1,"\
"cropBox=''"

exit 0
