#!/bin/bash
#
#PBS -N meshes
#PBS -A Your_Account_String
#PBS -l select=1:ncpus=2:mpiprocs=2:mem=10GB,walltime=5:00:00

(sleep $(( ($PBS_ARRAY_INDEX % 10) * 15 )))

numberStacksPerJob=10
lastStack=$(( ($numberStacksPerJob)*($PBS_ARRAY_INDEX) ))
firstStack=$(( ($lastStack)-($numberStacksPerJob)+1 ))

echo "job "$PBS_ARRAY_INDEX" stacks "$firstStack" - "$lastStack

~/Fiji.app/ImageJ-linux64 --ij2 --headless --allow-multiple --run ~/code/get_meshes.groovy \
"imageStackLocation='outputs/objectAnalysis/',"\
"savePath='/outputs/Meshes/',"\
"classesToAnalyse='[1,2,3,4]',"\
"firstStackNumber='$firstStack',"\
"lastStackNumber='$lastStack',"\
"numberThreadsToUse='2',"\
"stackNumberPrefix='-t',"\
"stackNumberSuffix='-e',"\
"fileNamePrefix='c1-',"\
"overwriteExisting='false',"\
"targetMeshVertexReduction='[0.96,0,0.8,0.8]',"\
"meshSmoothingIterations='[0,0,0,0]',"

exit 0
