#!/bin/bash
#
#PBS -N skeletons
#PBS -A Your_Account_String
#PBS -l select=1:ncpus=2:mpiprocs=2:mem=10GB,walltime=2:30:00

(sleep $(( ($PBS_ARRAY_INDEX % 10) * 15 )))
     
numberStacksPerJob=100
lastStack=$(( ($numberStacksPerJob)*($PBS_ARRAY_INDEX) ))
firstStack=$(( ($lastStack)-($numberStacksPerJob)+1 ))

echo "job "$PBS_ARRAY_INDEX" stacks "$firstStack" - "$lastStack

~/Fiji.app/ImageJ-linux64 --ij2 --headless --allow-multiple --run ~/code/get_skeletons.groovy \
"imageStackLocation='/outputs/objectAnalysis/',"\
"savePath='/outputs/objectAnalysis/skeletons/',"\
"classesToAnalyse='[2]',"\
"firstStackNumber='$firstStack',"\
"lastStackNumber='$lastStack',"\
"numberThreadsToUse='2',"\
"stackNumberPrefix='-t',"\
"stackNumberSuffix='-e',"\
"fileNamePrefix='c1-',"\
"overwriteExisting='false',"

exit 0
