#!/bin/bash
#
#PBS -N segment_20200728_MDA231control_2
#PBS -A UQ-IMB
#PBS -l select=1:ncpus=3:mpiprocs=3:mem=80GB,walltime=1:00:00


feature_model_table='/code/feature_model_table.txt'
imageStackLocation='/images/'
modelName='model_name'
modelPath='models/'
featurePath=$TMPDIR'/fs/'
savePath='/outputs/'
numberThreadsToUse='3'
saveProbabilityMaps='true'
stackNumberPrefix='t'
stackNumberSuffix='-e'
prefix='c1-'
pixelSize_unit='nm'
pixelSize_xy='104'
pixelSize_z='268.146'
intensityScalingFactor='2.49739854318418'
intensityScalingFactorTimeStep='1.00023326633857'
cropBox='205,823,211,741,0,154'
channel_grouping='[[0],[1],[2,3]]'
channels='4'

intensityScalingFactor=$(echo "$intensityScalingFactor $intensityScalingFactorTimeStep $PBS_ARRAY_INDEX" | awk '{print $1*($2^($3-1));}')

echo "PBS_ARRAY_INDEX (timestep) = "$PBS_ARRAY_INDEX
echo "Apply cropping box: "$cropBox
echo "Pixel dimensions: "$pixelSize_xy" (x,y); "$pixelSize_z" (z)"
echo "Adjusted intensityScalingFactor: "$intensityScalingFactor

imageStackName=$(ls $imageStackLocation | grep "$stackNumberPrefix"0*$PBS_ARRAY_INDEX"$stackNumberSuffix" | grep "^$prefix" | cut -d. -f1)

# CI_path_check=$savePath"Classified_Image_"$imageStackName"_"$modelName".tif"
CI_path_check=$savePath"segmented/"$imageStackName"_seg_"$modelName".tif"
if [ -f $CI_path_check ]; then
   echo "Segmented image already exists: exiting job"
   exit 0
fi


(sleep $(( ($PBS_ARRAY_INDEX % 10) * 15 )))

~/Fiji.app/ImageJ-linux64 --ij2 --headless --run ~/code/generate_save_features.groovy \
"feature_model_table='$feature_model_table',"\
"imageStackLocation='$imageStackLocation',"\
"imageStackName='$imageStackName',"\
"modelName='$modelName',"\
"featureSavePath='$featurePath',"\
"numberThreadsToUse='$numberThreadsToUse',"\
"pixelSize_xy='$pixelSize_xy',"\
"pixelSize_z='$pixelSize_z',"\
"intensityScalingFactor='$intensityScalingFactor',"\
"cropBox='$cropBox'"

~/Fiji.app/ImageJ-linux64 --ij2 --headless --run ~/code/apply_classifiers.groovy \
"feature_model_table='$feature_model_table',"\
"imageStackName='$imageStackName',"\
"featurePath='$featurePath',"\
"modelPath='$modelPath',"\
"modelName='$modelName',"\
"savePath='$savePath',"\
"numberThreadsToUse='$numberThreadsToUse',"\
"saveProbabilityMaps='$saveProbabilityMaps',"\
"pixelSize_unit='$pixelSize_unit',"\
"pixelSize_xy='$pixelSize_xy',"\
"pixelSize_z='$pixelSize_z',"\
"channel_grouping='$channel_grouping',"\
"channels='$channels'"

sleep 10s
