#!/bin/bash

echo "starting script get_tracks"
./Fiji.app/ImageJ-linux64 --ij2 --headless --allow-multiple --run ./code/get_tracks_parameterised.groovy \
"main_path='outputs/Segmentation/objectAnalysis/',"\
"save_path='outputs/Segmentation/objectAnalysis/trackNodeTable.csv',"\
"timeSteps_specified=[],"\
"breakPoints=[],"\
"useAlphabeticalPositionForStackNumber='false',"\
"stackNumPrefix='-t',"\
"stackNumSuffix='-e',"\
"fieldScaling=[1.04,1.04,2.68],"\
"trackedClasses=[1,2,3,4],"\
"voxelThresholds=[2000,30,200,200],"\
"logSizeWeight=[90,22,22,22],"\
"matchThreshold=[120,20,20,20],"\
"relativeNodeContact_referenceValue=[0.06,0.02,0.04,0.04],"\
"relativeNodeDistance_referenceValue=[0.7,0.5,0.8,0.8],"\
"relativeNodeContact_weight=[0.66,0.66,0.66,0.66],"\
"matchScoreWeighting=[0.35,0.25,0.25,0.25],"\
"verbose='true'"\
> tracks.log

echo "finished get_tracks job script"
exit
